export const UPDATE_DATA_NAME = "UPDATE_DATA_NAME";
export const UPDATE_ALGORITHM_NAME = "UPDATE_ALGORITHM_NAME";
export const DATA_LOADED = "DATA_LOADED";
export const ADD_PROTECTED_NODE = "ADD_PROTECTED_NODE";
export const DELETE_PROTECTED_NODE = "DELETED_PROTECTED_NODE";